"""
Unique identifier generation utilities.

This module provides functions for generating unique identifiers
used throughout the interview system.
"""

import uuid
import time
from datetime import datetime


def generate_interview_id() -> str:
    """
    Generate a unique interview session ID.
    
    Returns:
        String UUID4 identifier
    """
    return str(uuid.uuid4())


def generate_short_id(length: int = 8) -> str:
    """
    Generate a shorter unique identifier.
    
    Args:
        length: Desired length of the ID (default: 8)
        
    Returns:
        Short alphanumeric identifier
    """
    import secrets
    import string
    
    alphabet = string.ascii_letters + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(length))


def generate_timestamped_id(prefix: str = "") -> str:
    """
    Generate ID with timestamp for chronological ordering.
    
    Args:
        prefix: Optional prefix to add to the ID
        
    Returns:
        Timestamped identifier
    """
    timestamp = int(time.time() * 1000)  # milliseconds
    short_uuid = str(uuid.uuid4()).split('-')[0]
    
    if prefix:
        return f"{prefix}_{timestamp}_{short_uuid}"
    return f"{timestamp}_{short_uuid}"


def is_valid_uuid(uuid_string: str) -> bool:
    """
    Validate if a string is a valid UUID.
    
    Args:
        uuid_string: String to validate
        
    Returns:
        True if valid UUID, False otherwise
    """
    try:
        uuid.UUID(uuid_string)
        return True
    except (ValueError, TypeError):
        return False


def extract_timestamp_from_id(timestamped_id: str) -> datetime:
    """
    Extract timestamp from a timestamped ID.
    
    Args:
        timestamped_id: ID generated by generate_timestamped_id()
        
    Returns:
        Datetime object of when ID was created
        
    Raises:
        ValueError: If ID format is invalid
    """
    try:
        parts = timestamped_id.split('_')
        if len(parts) < 2:
            raise ValueError("Invalid timestamped ID format")
        
        # Find the timestamp part (should be numeric)
        timestamp_ms = None
        for part in parts:
            if part.isdigit() and len(part) >= 10:  # Unix timestamp in milliseconds
                timestamp_ms = int(part)
                break
        
        if timestamp_ms is None:
            raise ValueError("No valid timestamp found in ID")
        
        return datetime.fromtimestamp(timestamp_ms / 1000)
    
    except (ValueError, IndexError) as e:
        raise ValueError(f"Could not extract timestamp from ID '{timestamped_id}': {e}")


def generate_session_token() -> str:
    """
    Generate a secure session token.
    
    Returns:
        Cryptographically secure token
    """
    import secrets
    return secrets.token_urlsafe(32)


def sanitize_filename(filename: str) -> str:
    """
    Sanitize a string to be safe for use as a filename.
    
    Args:
        filename: Raw filename string
        
    Returns:
        Sanitized filename safe for filesystem use
    """
    import re
    
    # Remove or replace invalid characters
    filename = re.sub(r'[<>:"/\\|?*]', '_', filename)
    
    # Remove leading/trailing whitespace and dots
    filename = filename.strip('. ')
    
    # Ensure it's not empty
    if not filename:
        filename = f"unnamed_{generate_short_id(6)}"
    
    # Limit length
    if len(filename) > 200:
        filename = filename[:190] + f"_{generate_short_id(6)}"
    
    return filename


class IDGenerator:
    """
    Class-based ID generator with customizable patterns.
    """
    
    def __init__(self, prefix: str = "", suffix: str = ""):
        """
        Initialize ID generator with optional prefix/suffix.
        
        Args:
            prefix: String to prepend to generated IDs
            suffix: String to append to generated IDs
        """
        self.prefix = prefix
        self.suffix = suffix
    
    def generate(self) -> str:
        """Generate ID with configured prefix/suffix."""
        base_id = str(uuid.uuid4())
        
        parts = []
        if self.prefix:
            parts.append(self.prefix)
        parts.append(base_id)
        if self.suffix:
            parts.append(self.suffix)
        
        return '_'.join(parts)
    
    def generate_numeric(self, digits: int = 8) -> str:
        """
        Generate numeric ID with specified number of digits.
        
        Args:
            digits: Number of digits in the ID
            
        Returns:
            Numeric ID string
        """
        import random
        
        # Ensure first digit is not 0
        first_digit = random.randint(1, 9)
        remaining_digits = ''.join(str(random.randint(0, 9)) for _ in range(digits - 1))
        
        base_id = str(first_digit) + remaining_digits
        
        parts = []
        if self.prefix:
            parts.append(self.prefix)
        parts.append(base_id)
        if self.suffix:
            parts.append(self.suffix)
        
        return '_'.join(parts)


# Pre-configured generators for common use cases
interview_id_generator = IDGenerator(prefix="interview")
question_id_generator = IDGenerator(prefix="q")
session_id_generator = IDGenerator(prefix="session")


def get_interview_filename(interview_id: str) -> str:
    """
    Generate standardized filename for interview data.
    
    Args:
        interview_id: Interview session ID
        
    Returns:
        Filename for storing interview data
    """
    safe_id = sanitize_filename(interview_id)
    return f"{safe_id}.json"


if __name__ == "__main__":
    # Test the ID generation functions
    print("Testing ID generation utilities...")
    
    print(f"Interview ID: {generate_interview_id()}")
    print(f"Short ID: {generate_short_id()}")
    print(f"Timestamped ID: {generate_timestamped_id('test')}")
    print(f"Session token: {generate_session_token()}")
    
    # Test filename sanitization
    unsafe_name = "Interview: <John's Test> 2023/11/06"
    print(f"Unsafe: '{unsafe_name}' -> Safe: '{sanitize_filename(unsafe_name)}'")
    
    # Test ID generators
    interview_gen = IDGenerator(prefix="interview", suffix="v1")
    print(f"Custom interview ID: {interview_gen.generate()}")
    print(f"Numeric ID: {interview_gen.generate_numeric(6)}")
    
    print("All tests completed successfully!")